//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangman.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hangman.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap step0 {
            get {
                object obj = ResourceManager.GetObject("step0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap step1 {
            get {
                object obj = ResourceManager.GetObject("step1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap step2 {
            get {
                object obj = ResourceManager.GetObject("step2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap step3 {
            get {
                object obj = ResourceManager.GetObject("step3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap step4 {
            get {
                object obj = ResourceManager.GetObject("step4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap step5 {
            get {
                object obj = ResourceManager.GetObject("step5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap step6 {
            get {
                object obj = ResourceManager.GetObject("step6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap step7 {
            get {
                object obj = ResourceManager.GetObject("step7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to АБАЖУР
        ///АБАЗИНЕЦ
        ///АБАЗИНКА
        ///АББАТ
        ///АББАТИСА
        ///АББАТСТВО
        ///АББРЕВИАТУРА
        ///АБЕРРАЦИЯ
        ///АБЗАЦ
        ///АБИССИНЕЦ
        ///АБИССИНКА
        ///АБИТУРИЕНТ
        ///АБИТУРИЕНТКА
        ///АБОНЕМЕНТ
        ///АБОНЕНТ
        ///АБОНЕНТКА
        ///АБОРДАЖ
        ///АБОРИГЕН
        ///АБОРИГЕНКА
        ///АБОРТ
        ///АБОРТИВНОСТЬ
        ///АБРАЗИВ
        ///АБРАКАДАБРА
        ///АБРЕК
        ///АБРИКОС
        ///АБРИС
        ///АБСЕНТЕИЗМ
        ///АБСОЛЮТ
        ///АБСОЛЮТИЗМ
        ///АБСОЛЮТНОСТЬ
        ///АБСТРАКТНОСТЬ
        ///АБСТРАКЦИОНИЗМ
        ///АБСТРАКЦИОНИСТ
        ///АБСТРАКЦИОНИСТКА
        ///АБСТРАКЦИЯ
        ///АБСУРД
        ///АБСУРДНОСТЬ
        ///АБСЦЕСС
        ///АБХАЗ
        ///АБХАЗЕЦ
        ///АБХАЗКА
        ///АВАНГАРД
        ///АВАНГАРДИЗМ
        ///АВАНГАРДИСТ
        ///АВАНГАРДИСТКА
        ///АВАНЗАЛ
        ///АВАНЛОЖА
        ///АВАНПОРТ
        ///АВАНПОСТ
        ///АВАНС
        ///АВАНСЦЕНА
        ///АВАНТЮРА
        ///АВА [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string файл_со_словами {
            get {
                return ResourceManager.GetString("файл_со_словами", resourceCulture);
            }
        }
    }
}
